### ISSUE TITLE
Remove effect chance

### ISSUE THREAD

**Issue by Foreck1** [fonnymunkey/EditableEdibles#1]
If you've played with the Rats mod, you might know that it adds a plague effect and some remedy items that have a chance to remove that effect; the same goes with milk in vanilla for most potion effects. I say you could expand this behavior using this mod to define the following: 

Food Cure Effect: List of entries including the item, potion effect to be cured, up to what amplifier level it can cure the effect (-1 for any), and the chance to cure.
    Format: String itemId, Int metadata (-1 for any), String potionId, Int amplifier, Float chance
    Example: minecraft:beetroot, -1, rats:plague, 2, 0.5

This can further be used with mods that nerf milk to specify different food items to counter different negative effects.

**Comment by fonnymunkey** [comment]
Added and expanded on this in 6e50a7c , thanks for the suggestion.
