### ISSUE TITLE
Misty World Intoxication and Chemical Pollution support

### ISSUE THREAD

**Issue by fullskele** [fonnymunkey/EditableEdibles#2]
In the Misty World mod, there are two detrimental statuses the player can accrue over time, named Intoxication and (Chemical) Pollution. Intoxication is reduced by eating select foods from the Misty World (and Pollution is reduced by bathing in water).

There exists a command: `/setmisteffects <player> <effect> [amount]` , which would be useful with CraftTweaker to allow for certain foods to reduce the player's current statuses, however it functions by setting a players' status to the given percent, and has no option to simply add or take away an amount from their current statuses. Would it be possible to add two entry types to make a food item add or reduce a Misty World status by a given percent? Thank you!

The format for a status could go as follows:
`String itemId, Int metadata (-1 for any), Int modifyPercent (range of -100 to 100), Float chance`

Some examples:
```
minecraft:golden_apple, -1, -20, 100     //Takes 20% away from Intoxication every time
minecraft:rotten_flesh, -1, 5, 50     //Adds 5% to Chemical Pollution half of the time
```
Misty World repository:
https://github.com/Liahim85/MistyWorld_Open

**Comment by fonnymunkey** [comment]
Added with f78f93f , thanks for the suggestion.
